import { type IMedicationSchema } from '@/stores/schemas'

export const medications: IMedicationSchema[] = [
    {
        id: 1,
        slug: 'bicarbonate-1',
        label: 'Бикарбонат 1',
        takingMethod: 'intravenously',
        volume: 200,
        unit: 'гр',
        dosage: 200,
        groupSlug: 'bicarbonates',
        categorySlug: 'bicarbonates',
    },
    {
        id: 2,
        slug: 'bicarbonate-2',
        label: 'Бикарбонат 2',
        takingMethod: 'intravenously',
        volume: 300,
        unit: 'л',
        dosage: 300,
        groupSlug: 'bicarbonates',
        categorySlug: 'bicarbonates',
    },
    {
        id: 3,
        slug: 'bicarbonate-3',
        label: 'Бикарбонат 3',
        takingMethod: 'intravenously',
        volume: 150,
        unit: 'гр',
        dosage: 150,
        groupSlug: 'bicarbonates',
        categorySlug: 'bicarbonates',
    },
    {
        id: 4,
        slug: 'anticoagulant-1',
        label: 'Антикоагулянт 1',
        takingMethod: 'intravenously',
        volume: 150,
        unit: 'ед',
        dosage: 150,
        groupSlug: 'anticoagulants',
        categorySlug: 'anticoagulants',
    },
    {
        id: 5,
        slug: 'anticoagulant-2',
        label: 'Антикоагулянт 2',
        takingMethod: 'intravenously',
        volume: 200,
        unit: 'ед',
        dosage: 200,
        groupSlug: 'anticoagulants',
        categorySlug: 'anticoagulants',
    },
    {
        id: 6,
        slug: 'anticoagulant-3',
        label: 'Антикоагулянт 3',
        takingMethod: 'intravenously',
        volume: 320,
        unit: 'ед',
        dosage: 320,
        groupSlug: 'anticoagulants',
        categorySlug: 'anticoagulants',
    },
]
